name: Java CI

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  schedule:
    - cron: "0 4 * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest  # latest Ubuntu environment on GitHub's runners

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      # Step 2: Set up Java JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' 
          distribution: 'temurin' 
          
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/src/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 3: Compile the Java file
      - name: Compile Java Program
        run: |
          javac Main.java  # Adjust this path based on where your Java file is

      # Step 4: Run the Java Program
      - name: Run Java Program
        run: |
          java Main  # Run the main class, adjust the package path if necessary
      # - name: commit
      #  run: |- 
      #    git add .github/workflows/java.yml
      #    git commit -m "Add GitHub Actions workflow to build and run Java program"
      #    git push origin main
