name: Java CI

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
 # schedule:
 #   - cron: "0 4 * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest  # latest Ubuntu environment on GitHub's runners

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' 
          distribution: 'temurin' 
          
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/src/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Compile Java Program
        run: |
          javac Main.java  
  
      - name: Run Java Program
        run: |
          java Main  
      # - name: commit
      #  run: |- 
      #    git add .github/workflows/java.yml
      #    git commit -m "Add GitHub Actions workflow to build and run Java program"
      #    git push origin main
